/**************************************************************************************************
 * Name           : GS_OppLineItemDMLHandler
 * Object         : Asset/Opp Product
 *Requirement    : SPS-1082
 * Target         : Opporutnity DML Handler
 * Refer classes  :
 * Author         : Uday Bikkumalla
 * Create Date    : 2015-08-03
 * Modify History :
 **************************************************************************************************/
public class GS_OppLineItemDMLHandler {
  /* public static List<OpportunityLineItem> getLineItemsByAssets(List<Asset> assets) {
        return [SELECT id
                ,Name
                ,Reason_for_RAG_Status__c
                ,Asset__r.Reason_for_RAG_Status__c
                FROM OpportunityLineItem
                WHERE Asset__c in: assets   
               ];
    }*/
}